version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: grupoa
    container_name: grupoa-app
    restart: unless-stopped
    networks:
      - grupoa
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: grupoa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - grupoa-database:/var/lib/mysql
    networks:
      - grupoa

networks:
  grupoa:
    driver: bridge

volumes:
  grupoa-database:
